// <auto-generated />
using MSGM.Models.ContextMusic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSGM.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSGM.Models.Data.Games", b =>
                {
                    b.Property<int>("GamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Available")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Developer")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DtLaunch")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GenreGames")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("SM")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("GamesId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MSGM.Models.Data.Movies", b =>
                {
                    b.Property<int>("MoviesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Available")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DtLaunch")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GenreMovies")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MainCharacters")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("MoviesId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MSGM.Models.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RePassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MSGM.Models.Music", b =>
                {
                    b.Property<int>("MusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Available")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DtLaunch")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GenreMusic")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LinkMusic")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Singer")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MusicId");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("MSGM.Models.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Available")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DtLaunch")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GenreSeries")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Seasons")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("SeriesId");

                    b.ToTable("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
